# Site settings

title: Multiscale Modeling of Materials
header-img: img/home-bg.jpg
email: latmarat@gmail.com
description: "Physics-based models and simulations for process-structure-property linkages"
baseurl: "/simulations-modeling"
url: "http://mined-gatech.github.io"
github_username:  latmarat
project_repository: simulations-modeling

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
