# Site settings

title: Two-Phase Composite Structure Property Linkage Establishment
header-img: img/home-bg1.jpg
email: dmo7@gatech.edu
description: "Physics-based models and simulations for process-structure-property linkages"
baseurl: "/GT-Sandia_Collaboration"
url: "http://dmontesdocaz.github.io"
github_username:  dmontesdocaz
project_repository: GT-Sandia_Collaboration

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: 'rouge' 
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
